replicaCount: 1

image:
  repository: yardengz/hello-go
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: hello-go
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

env:
  - name: APP_PORT
    value: "8080"

livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /readiness
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 5
